version: "3.3"

services:
  database:
    container_name: djmenu
    image: postgres
    restart: always
    volumes:
    - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=djmenu
      - POSTGRES_USER=djmenu
    ports:
      - 5432:5432