# Generated by Django 3.0.7 on 2020-06-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20191124_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, help_text='Preenchido automaticamente, não editar', max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
    ]
